name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build all applications
        env:
          NODE_ENV: production
        run: |
          npx nx build container --configuration=production --base-href=/budget-planner/ --output-hashing=none
          npx nx build mfeDashboard --configuration=production --base-href=/budget-planner/ --output-hashing=none
          npx nx build mfeBudget --configuration=production --base-href=/budget-planner/ --output-hashing=none
          npx nx build mfeReports --configuration=production --base-href=/budget-planner/ --output-hashing=none
          npx nx build mfeSettings --configuration=production --base-href=/budget-planner/ --output-hashing=none

      - name: Prepare deployment
        run: |
          mkdir -p dist/github-pages
          cp -r dist/container/* dist/github-pages/
          mkdir -p dist/github-pages/mfeDashboard
          mkdir -p dist/github-pages/mfeBudget
          mkdir -p dist/github-pages/mfeReports
          mkdir -p dist/github-pages/mfeSettings
          cp -r dist/mfeDashboard/* dist/github-pages/mfeDashboard/
          cp -r dist/mfeBudget/* dist/github-pages/mfeBudget/
          cp -r dist/mfeReports/* dist/github-pages/mfeReports/
          cp -r dist/mfeSettings/* dist/github-pages/mfeSettings/
          
          # Rename remote entry files from .mjs to .js
          for app in mfeDashboard mfeBudget mfeReports mfeSettings; do
            if [ -f "dist/github-pages/$app/remoteEntry.mjs" ]; then
              mv "dist/github-pages/$app/remoteEntry.mjs" "dist/github-pages/$app/remoteEntry.js"
            fi
          done

          # Create _headers file for CORS
          echo "/*
            Access-Control-Allow-Origin: *
            Access-Control-Allow-Methods: GET, OPTIONS
            Access-Control-Allow-Headers: *" > dist/github-pages/_headers

          # Create .nojekyll file to prevent Jekyll processing
          touch dist/github-pages/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/github-pages
          enable_jekyll: false 